[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
  # By file Path
  './out/kolonihaver-til-salg.html',
]
