// import type { Metadata } from "next";
import { Fauna_One } from "next/font/google";
import Nav from "./components/nav";
import "./style/globals.css";
import "./style/style.scss";

const bodyfont = Fauna_One({ subsets: ["latin"], weight: "400" });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function SharedLayout({ children }) {
  return (
    // <html lang="en">
    //   <body>
    <div
      style={{
        "--headerfont": bodyfont.style.fontFamily,
      }}
      className="page-wrapper"
    >
      <link rel="stylesheet" href="https://use.typekit.net/ifv8bnn.css"></link>
      {/* <svg width="10" height="10" viewBox="0 0 10 10">
        <clipPath id="squircleClip" clipPathUnits="objectBoundingBox">
          <path fill="red" stroke="none" d="M 0,0.5 C 0,0 0,0 0.5,0 S 1,0 1,0.5 1,1 0.5,1 0,1 0,0.5" />
        </clipPath>
      </svg> */}
      <Nav />
      {children}
    </div>
    //   </body>
    // </html>
  );
}
